#BSUB -J mcsim_1			## sets the job name
#BSUB -L /bin/bash			## uses the bash login shell to initialize the job's execution environment.
#BSUB -W 30:00				## sets to 30 hours the job's runtime wall-clock limit.
#BSUB -n 4					## assigns 4 cores for execution.
#BSUB -R "span[ptile=4]"    ## request 4 core per node.
#BSUB -R "rusage[mem=1024]"	## reserves 1024MB per process/CPU for the job 
#BSUB -M 1024				## sets to 1024MB as the per process enforceable memory limit.
#BSUB -o stdout_1.%J		## directs the job's standard output (%J is jobid)

./mcsim.APAP apap.p21.c1.in & ./mcsim.APAP apap.p21.c2.in & ./mcsim.APAP apap.p21.c3.in & ./mcsim.APAP apap.p21.c4.in 
wait
