#BSUB -J mcsim_1			## sets the job name
#BSUB -L /bin/bash			## uses the bash login shell to initialize the job's execution environment.
#BSUB -W 20:00				## sets to 20 hours the job's runtime wall-clock limit.
#BSUB -n 4					## assigns 4 cores for execution.
#BSUB -R "span[ptile=4]"    ## Request 4 core per node.
#BSUB -R "rusage[mem=500]"	## reserves 500MB per process/CPU for the job 
#BSUB -M 500				## sets to 500MB as the per process enforceable memory limit.
#BSUB -o stdout_1.%J		## directs the job's standard output (%J is jobid)

./mcsim.TCE.2.13 TCE.2.13.pop_1.in & ./mcsim.TCE.2.13 TCE.2.13.pop_2.in & ./mcsim.TCE.2.13 TCE.2.13.pop_3.in
wait
